export const movieAdapter = (movie) => ({
  id: movie.id,
  title: movie.name,
  runTime: movie.run_time,
  genre: movie.genre,
  releaseDate: movie.released,
  poster: movie.poster_image,
  previewImage: movie.preview_image,
  backgroundImage: movie.background_image,
  backgroundColor: movie.background_color,
  ratingScore: movie.rating,
  ratingCount: movie.scores_count,
  description: movie.description,
  director: movie.director,
  stars: movie.starring,
  preview: movie.preview_video_link,
  video: movie.video_link,
  isFavorite: movie.is_favorite,
});
